import type { EditorThemeClasses } from 'lexical';

export const editorTheme: EditorThemeClasses = {
  root: 'lexical-editor',
  paragraph: 'mb-4 text-white leading-relaxed',
  heading: {
    h1: 'text-4xl font-bold text-white mb-6 mt-8',
    h2: 'text-3xl font-bold text-white mb-5 mt-7',
    h3: 'text-2xl font-semibold text-white mb-4 mt-6',
    h4: 'text-xl font-semibold text-white mb-3 mt-5',
    h5: 'text-lg font-medium text-white mb-2 mt-4',
    h6: 'text-base font-medium text-white mb-2 mt-3',
  },
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'bg-[#1A1A1A] text-[#D4AF37] px-1.5 py-0.5 rounded font-mono text-sm',
  },
  link: 'text-[#D4AF37] hover:text-[#E5C158] underline cursor-pointer',
  list: {
    ul: 'list-disc list-inside mb-4 space-y-1 text-white',
    ol: 'list-decimal list-inside mb-4 space-y-1 text-white',
    listitem: 'ml-4',
    nested: {
      listitem: 'ml-6',
    },
    checklist: 'list-none space-y-2',
    listitemChecked: 'line-through text-gray-500',
    listitemUnchecked: '',
  },
  quote: 'border-l-4 border-[#D4AF37] pl-4 italic text-gray-300 my-4',
  code: 'bg-[#1A1A1A] rounded-lg p-4 font-mono text-sm overflow-x-auto my-4',
  codeHighlight: {
    atrule: 'text-purple-400',
    attr: 'text-yellow-400',
    boolean: 'text-orange-400',
    builtin: 'text-cyan-400',
    cdata: 'text-gray-500',
    char: 'text-green-400',
    class: 'text-yellow-400',
    'class-name': 'text-yellow-400',
    comment: 'text-gray-500 italic',
    constant: 'text-orange-400',
    deleted: 'text-red-400',
    doctype: 'text-gray-500',
    entity: 'text-red-400',
    function: 'text-blue-400',
    important: 'text-orange-400 font-bold',
    inserted: 'text-green-400',
    keyword: 'text-purple-400',
    namespace: 'text-red-400',
    number: 'text-orange-400',
    operator: 'text-cyan-400',
    prolog: 'text-gray-500',
    property: 'text-cyan-400',
    punctuation: 'text-gray-400',
    regex: 'text-red-400',
    selector: 'text-green-400',
    string: 'text-green-400',
    symbol: 'text-orange-400',
    tag: 'text-red-400',
    url: 'text-cyan-400',
    variable: 'text-red-400',
  },
  table: 'border-collapse w-full my-4',
  tableCell: 'border border-white/20 px-3 py-2 text-white',
  tableCellHeader: 'bg-[#1A1A1A] font-semibold text-white border border-white/20 px-3 py-2',
  tableRow: 'border-b border-white/10',
  image: 'max-w-full h-auto rounded-lg my-4',
  hr: 'border-t border-white/20 my-6',
};



